<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260130225423 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE decoration (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, awarded_at DATE NOT NULL, awarded_by VARCHAR(255) DEFAULT NULL, certificate_number VARCHAR(100) DEFAULT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, member_id INT NOT NULL, type_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7649DA77597D3FE ON decoration (member_id)');
        $this->addSql('CREATE INDEX IDX_7649DA7C54C8C93 ON decoration (type_id)');
        $this->addSql('CREATE TABLE decoration_dictionary (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, category VARCHAR(20) NOT NULL, required_years INT DEFAULT NULL, sort_order INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE equipment_dictionary (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, category VARCHAR(20) NOT NULL, has_sizes BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE personal_equipment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, size VARCHAR(20) DEFAULT NULL, serial_number VARCHAR(100) DEFAULT NULL, issued_at DATE NOT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, member_id INT NOT NULL, type_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DC9413697597D3FE ON personal_equipment (member_id)');
        $this->addSql('CREATE INDEX IDX_DC941369C54C8C93 ON personal_equipment (type_id)');
        $this->addSql('ALTER TABLE decoration ADD CONSTRAINT FK_7649DA77597D3FE FOREIGN KEY (member_id) REFERENCES member (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE decoration ADD CONSTRAINT FK_7649DA7C54C8C93 FOREIGN KEY (type_id) REFERENCES decoration_dictionary (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE personal_equipment ADD CONSTRAINT FK_DC9413697597D3FE FOREIGN KEY (member_id) REFERENCES member (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE personal_equipment ADD CONSTRAINT FK_DC941369C54C8C93 FOREIGN KEY (type_id) REFERENCES equipment_dictionary (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE decoration DROP CONSTRAINT FK_7649DA77597D3FE');
        $this->addSql('ALTER TABLE decoration DROP CONSTRAINT FK_7649DA7C54C8C93');
        $this->addSql('ALTER TABLE personal_equipment DROP CONSTRAINT FK_DC9413697597D3FE');
        $this->addSql('ALTER TABLE personal_equipment DROP CONSTRAINT FK_DC941369C54C8C93');
        $this->addSql('DROP TABLE decoration');
        $this->addSql('DROP TABLE decoration_dictionary');
        $this->addSql('DROP TABLE equipment_dictionary');
        $this->addSql('DROP TABLE personal_equipment');
    }
}
