<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260131065215 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE financial_category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(20) NOT NULL, sort_order INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE financial_record (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(20) NOT NULL, amount NUMERIC(10, 2) NOT NULL, description TEXT NOT NULL, document_number VARCHAR(100) DEFAULT NULL, recorded_at DATE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, category_id INT NOT NULL, created_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3094C32212469DE2 ON financial_record (category_id)');
        $this->addSql('CREATE INDEX IDX_3094C322B03A8386 ON financial_record (created_by_id)');
        $this->addSql('ALTER TABLE financial_record ADD CONSTRAINT FK_3094C32212469DE2 FOREIGN KEY (category_id) REFERENCES financial_category (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE financial_record ADD CONSTRAINT FK_3094C322B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE financial_record DROP CONSTRAINT FK_3094C32212469DE2');
        $this->addSql('ALTER TABLE financial_record DROP CONSTRAINT FK_3094C322B03A8386');
        $this->addSql('DROP TABLE financial_category');
        $this->addSql('DROP TABLE financial_record');
    }
}
