<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260130194219 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE member (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, pesel VARCHAR(11) NOT NULL, address TEXT DEFAULT NULL, phone VARCHAR(20) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, birth_date DATE NOT NULL, join_date DATE NOT NULL, death_date DATE DEFAULT NULL, membership_status VARCHAR(20) NOT NULL, board_position VARCHAR(100) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_70E4FA783931747B ON member (pesel)');
        $this->addSql('CREATE TABLE membership_fee (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, year INT NOT NULL, amount NUMERIC(10, 2) NOT NULL, status VARCHAR(20) NOT NULL, paid_at DATE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, member_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1857017F7597D3FE ON membership_fee (member_id)');
        $this->addSql('CREATE UNIQUE INDEX member_year_unique ON membership_fee (member_id, year)');
        $this->addSql('ALTER TABLE membership_fee ADD CONSTRAINT FK_1857017F7597D3FE FOREIGN KEY (member_id) REFERENCES member (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE membership_fee DROP CONSTRAINT FK_1857017F7597D3FE');
        $this->addSql('DROP TABLE member');
        $this->addSql('DROP TABLE membership_fee');
    }
}
